const images = {
    adCube: {
        btnDisplayInactive: require('../resources/images/adcube/but_display.png'),
        btnDisplayActive: require('../resources/images/adcube/but_display_f2.png'),
        btnSopnsored: require('../resources/images/adcube/sponsored.png'),
        spacer: require('../resources/images/adcube/sponsored_f3.png'),
        timer: require('../resources/images/adcube/timer.png'),
        timerDimmer: require('../resources/images/INT/TIM/TIMER_GREY_TYR.png'),
        wwwButton: require('../resources/images/adcube/but_www.png'),
    },
    btnVideoInactive: require('../resources/images/INT/BUT/B1_VID_0.png'),
    btnVideoActive: require('../resources/images/INT/BUT/B1_VID_1.png'),
    btnAudioInactive: require('../resources/images/INT/BUT/B2_AUD_0.png'),
    btnAudioActive: require('../resources/images/INT/BUT/B2_AUD_1.png'),
    btnPlaylistInactive: require('../resources/images/INT/BUT/B4_PLA_0.png'),
    btnPlaylistActive: require('../resources/images/INT/BUT/B4_PLA_1.png'),
    btnVideoNotAvailable: require('../resources/images/INT/BUT/cubebutvideonotavail.png'),
    btnVideoInactive_sm: require('../resources/images/INT/BUT/cubeButSmallVideoOff.png'),
    btnVideoActive_sm: require('../resources/images/INT/BUT/cubeButSmallVideoOn.png'),
    btnAudioInactive_sm: require('../resources/images/INT/BUT/cubeButSmallAudioOff.png'),
    btnAudioActive_sm: require('../resources/images/INT/BUT/cubeButSmallAudioOn.png'),
    btnPlaylistInactive_sm: require('../resources/images/INT/BUT/cubeButSmallPlaylistOff.png'),
    btnPlaylistActive_sm: require('../resources/images/INT/BUT/cubeButSmallPlaylistOn.png'),
    timer: require('../resources/images/INT/TIM/TIMER_GREY_TYR.png'),
    videoBg: require('../resources/images/background.png'),
    logo: require('../resources/images/LOGO_TYR_v1A_padded_1000sq_yellow.png'),
    loginLogo: require('../resources/images/tethyr-logo.png'),
    playlistControlsDotOff: require('../resources/images/playlistControlsDotOff.png'),
    playlistControlsDotOn: require('../resources/images/playlistControlsDotOn.png'),
    playlistControlsDrag: require('../resources/images/playlistControlsDrag.png'),
    playlistControlsHideOn: require('../resources/images/playlistControlsHideOn.png'),
    playlistControlsHideOff: require('../resources/images/playlistControlsHideOff.png'),
    playlistControlsTrash: require('../resources/images/playlistControlsTrash.png'),
    interface_link: require('../resources/images/interface_link.png'),
    minBtn: require('../resources/images/win10_butMin.png'),
    broken : require('../resources/images/broken_500px.png'),
    addNewPlaylist : require('../resources/images/addNewPlaylist_500px.png'),
    placeholderAuthorImg : require('../resources/images/authorImg/placeholderAuthorImg.png'),
    placeholderThumb : require('../resources/images/thumbs/placeholderThumb.png'),

    btnAdCubeFullScreenOn : require('../resources/images/adcube/but_fullscreen_on.png'),
    btnAdCubeFullScreenOff : require('../resources/images/adcube/but_fullscreen_off.png'),
    btnAdCubeSubscribeOn : require('../resources/images/adcube/but_subscribe_on.png'),
    btnAdCubeSubscribeOff : require('../resources/images/adcube/but_subscribe_off.png'),
    btnAdCubeSponsored : require('../resources/images/adcube/sponsored.png'),
    markAudioCubeAudio : require('../resources/images/audiocube/audio.png'),
    btnAudioCubeAudioOn : require('../resources/images/audiocube/but_audio_s3.png'),
    btnAudioCubeAudioOff : require('../resources/images/audiocube/but_audio_off.png'),
    btnAudioCubeLockedAudioOn : require('../resources/images/audiocube/but_lockedaudio_on.png'),
    btnAudioCubeLockedAudioOff : require('../resources/images/audiocube/but_lockedaudio_off.png'),
    btnAudioCubePlaylistOn : require('../resources/images/audiocube/but_playlist_on.png'),
    btnAudioCubePlaylistOff : require('../resources/images/audiocube/but_playlist_off.png'),
    audioCubeMockup : require('../resources/images/audiocube_mock.gif'),
    adCubeMockup : require('../resources/images/adcube_mock.gif'),
    tethyrLogo : require('../resources/images/logo_tethyr.png'),
    tethyrMobileLogo : require('../resources/images/logo_tethyr_mobile.png'),
    andmoorLogo : require('../resources/images/logo_andmoor.png'),
    btnG1 : require('../resources/images/layouts/G1.png'),
    btnG2 : require('../resources/images/layouts/G2.png'),
    btnG2c1 : require('../resources/images/layouts/G2c1.png'),
    btnG3c1 : require('../resources/images/layouts/G3c1.png'),
    btnG4 : require('../resources/images/layouts/G4.png'),
    btnG4pro : require('../resources/images/layouts/G4pro.png'),
    btnG4c1 : require('../resources/images/layouts/G4c1.png'),
    btnG6 : require('../resources/images/layouts/G6.png'),
    btnG8 : require('../resources/images/layouts/G8.png'),
    btnM1 : require('../resources/images/layouts/M1.png'),
    btnM4 : require('../resources/images/layouts/M4.png'),
    btnG1_rollover : require('../resources/images/layouts/G1_rollover.png'),
    btnG2_rollover : require('../resources/images/layouts/G2_rollover.png'),
    btnG2c1_rollover : require('../resources/images/layouts/G2c1_rollover.png'),
    btnG3c1_rollover : require('../resources/images/layouts/G3c1_rollover.png'),
    btnG4_rollover : require('../resources/images/layouts/G4_rollover.png'),
    btnG4pro_rollover : require('../resources/images/layouts/G4pro_rollover.png'),
    btnG4c1_rollover : require('../resources/images/layouts/G4c1_rollover.png'),
    btnG6_rollover : require('../resources/images/layouts/G6_rollover.png'),
    btnG8_rollover : require('../resources/images/layouts/G8_rollover.png'),
    btnM1_rollover : require('../resources/images/layouts/M1_rollover.png'),
    btnM4_rollover : require('../resources/images/layouts/M4_rollover.png'),
    btnG1_active : require('../resources/images/layouts/G1_active.png'),
    btnG2_active : require('../resources/images/layouts/G2_active.png'),
    btnG2c1_active : require('../resources/images/layouts/G2c1_active.png'),
    btnG3c1_active : require('../resources/images/layouts/G3c1_active.png'),
    btnG4_active : require('../resources/images/layouts/G4_active.png'),
    btnG4pro_active : require('../resources/images/layouts/G4pro_active.png'),
    btnG4c1_active : require('../resources/images/layouts/G4c1_active.png'),
    btnG6_active : require('../resources/images/layouts/G6_active.png'),
    btnG8_active : require('../resources/images/layouts/G8_active.png'),
    btnM1_active : require('../resources/images/layouts/M1_active.png'),
    btnM4_active : require('../resources/images/layouts/M4_active.png'),
    bars : require('../resources/images/bars.png'),

    btnSettingTextLg : require('../resources/images/settingsbar/settingsbar_text_lg.png'),
    btnSettingTextLg_active : require('../resources/images/settingsbar/settingsbar_text_lg_active.png'),
    btnSettingTextLg_rollover : require('../resources/images/settingsbar/settingsbar_text_lg_rollover.png'),
    btnSettingTextMd : require('../resources/images/settingsbar/settingsbar_text_md.png'),
    btnSettingTextMd_active : require('../resources/images/settingsbar/settingsbar_text_md_active.png'),
    btnSettingTextMd_rollover : require('../resources/images/settingsbar/settingsbar_text_md_rollover.png'),
    btnSettingTextSm : require('../resources/images/settingsbar/settingsbar_text_sm.png'),
    btnSettingTextSm_active : require('../resources/images/settingsbar/settingsbar_text_sm_active.png'),
    btnSettingTextSm_rollover : require('../resources/images/settingsbar/settingsbar_text_sm_rollover.png'),

    btnSettingThumbLg : require('../resources/images/settingsbar/settingsbar_thumb_lg.png'),
    btnSettingThumbLg_active : require('../resources/images/settingsbar/settingsbar_thumb_lg_active.png'),
    btnSettingThumbLg_rollover : require('../resources/images/settingsbar/settingsbar_thumb_lg_rollover.png'),
    btnSettingThumbMd : require('../resources/images/settingsbar/settingsbar_thumb_md.png'),
    btnSettingThumbMd_active : require('../resources/images/settingsbar/settingsbar_thumb_md_active.png'),
    btnSettingThumbMd_rollover : require('../resources/images/settingsbar/settingsbar_thumb_md_rollover.png'),
    btnSettingThumbSm : require('../resources/images/settingsbar/settingsbar_thumb_sm.png'),
    btnSettingThumbSm_active : require('../resources/images/settingsbar/settingsbar_thumb_sm_active.png'),
    btnSettingThumbSm_rollover : require('../resources/images/settingsbar/settingsbar_thumb_sm_rollover.png'),

    btn_playlist_group_action : require('../resources/images/proghead/btn_playlist_group_action.png'),
    btn_timer_off : require('../resources/images/proghead/timer_off.png'),
    btn_timer_on : require('../resources/images/proghead/timer_on.png'),

    btnProgHeadLogoAnd : require('../resources/images/proghead/proghead_logo_and.png'),
    btnProgHeadLogoAndIcon : require('../resources/images/proghead/proghead_logo_and_icon.png'),
    btnProgHeadLogoTyr : require('../resources/images/proghead/proghead_logo_tyr.png'),
    btnProgHeadLogoTyrIcon : require('../resources/images/proghead/proghead_logo_tyr_icon.png'),
    btnProgHeadGridset : require('../resources/images/proghead/proghead_gridset.png'),
    btnProgHeadGridset_active : require('../resources/images/proghead/proghead_gridset_active.png'),
    btnProgHeadGridset_rollover : require('../resources/images/proghead/proghead_gridset_rollover.png'),
    btnProgHeadModeManager : require('../resources/images/proghead/proghead_mode_manager.png'),
    btnProgHeadModeManager_active : require('../resources/images/proghead/proghead_mode_manager_active.png'),
    btnProgHeadModeManager_rollover : require('../resources/images/proghead/proghead_mode_manager_rollover.png'),
    btnProgHeadModeSettings : require('../resources/images/proghead/proghead_mode_settings.png'),
    btnProgHeadModeSettings_active : require('../resources/images/proghead/proghead_mode_settings_active.png'),
    btnProgHeadModeSettings_rollover : require('../resources/images/proghead/proghead_mode_settings_rollover.png'),
    btnProgHeadModeViewer : require('../resources/images/proghead/proghead_mode_viewer.png'),
    btnProgHeadModeViewer_active : require('../resources/images/proghead/proghead_mode_viewer_active.png'),
    btnProgHeadModeViewer_rollover : require('../resources/images/proghead/proghead_mode_viewer_rollover.png'),
    
    btnProgHeadModeTour : require('../resources/images/proghead/proghead_mode_tour.png'),
    btnProgHeadModeTour_active : require('../resources/images/proghead/proghead_mode_tour_active.png'),
    btnProgHeadModeTour_rollover : require('../resources/images/proghead/proghead_mode_tour_rollover.png'),
    
    btnProgHeadUser : require('../resources/images/proghead/proghead_user.png'),
    btnProgHeadUser_active : require('../resources/images/proghead/proghead_user_active.png'),
    btnProgHeadUser_rollover : require('../resources/images/proghead/proghead_user_rollover.png'),
    btnProgHeadG1 : require('../resources/images/proghead/proghead_layout_G1pro.png'),
    btnProgHeadG1_active : require('../resources/images/proghead/proghead_layout_G1pro_active.png'),
    btnProgHeadG1_rollover : require('../resources/images/proghead/proghead_layout_G1pro_rollover.png'),
    btnProgHeadG2 : require('../resources/images/proghead/proghead_layout_G2.png'),
    btnProgHeadG2_active : require('../resources/images/proghead/proghead_layout_G2_active.png'),
    btnProgHeadG2_rollover : require('../resources/images/proghead/proghead_layout_G2_rollover.png'),
    btnProgHeadG2c1 : require('../resources/images/proghead/proghead_layout_G2c1.png'),
    btnProgHeadG2c1_active : require('../resources/images/proghead/proghead_layout_G2c1_active.png'),
    btnProgHeadG2c1_rollover : require('../resources/images/proghead/proghead_layout_G2c1_rollover.png'),
    btnProgHeadG3c1 : require('../resources/images/proghead/proghead_layout_G3c1.png'),
    btnProgHeadG3c1_active : require('../resources/images/proghead/proghead_layout_G3c1_active.png'),
    btnProgHeadG3c1_rollover : require('../resources/images/proghead/proghead_layout_G3c1_rollover.png'),
    btnProgHeadG4c1 : require('../resources/images/proghead/proghead_layout_G4c1.png'),
    btnProgHeadG4c1_active : require('../resources/images/proghead/proghead_layout_G4c1_active.png'),
    btnProgHeadG4c1_rollover : require('../resources/images/proghead/proghead_layout_G4c1_rollover.png'),
    btnProgHeadG4 : require('../resources/images/proghead/proghead_layout_G4.png'),
    btnProgHeadG4_active : require('../resources/images/proghead/proghead_layout_G4_active.png'),
    btnProgHeadG4_rollover : require('../resources/images/proghead/proghead_layout_G4_rollover.png'),
    btnProgHeadG4pro : require('../resources/images/proghead/proghead_layout_G4pro.png'),
    btnProgHeadG4pro_active : require('../resources/images/proghead/proghead_layout_G4pro_active.png'),
    btnProgHeadG4pro_rollover : require('../resources/images/proghead/proghead_layout_G4pro_rollover.png'),
    btnProgHeadG6 : require('../resources/images/proghead/proghead_layout_G6.png'),
    btnProgHeadG6_active : require('../resources/images/proghead/proghead_layout_G6_active.png'),
    btnProgHeadG6_rollover : require('../resources/images/proghead/proghead_layout_G6_rollover.png'),
    btnProgHeadG8 : require('../resources/images/proghead/proghead_layout_G8.png'),
    btnProgHeadG8_active : require('../resources/images/proghead/proghead_layout_G8_active.png'),
    btnProgHeadG8_rollover : require('../resources/images/proghead/proghead_layout_G8_rollover.png'),
    btnProgHeadM1 : require('../resources/images/proghead/proghead_layout_M1.png'),
    btnProgHeadM1_active : require('../resources/images/proghead/proghead_layout_M1_active.png'),
    btnProgHeadM1_rollover : require('../resources/images/proghead/proghead_layout_M1_rollover.png'),
    btnProgHeadM4 : require('../resources/images/proghead/proghead_layout_M4.png'),
    btnProgHeadM4_active : require('../resources/images/proghead/proghead_layout_M4_active.png'),
    btnProgHeadM4_rollover : require('../resources/images/proghead/proghead_layout_M4_rollover.png'),


    btnPlaylistFeatureOn : require('../resources/images/playlistheader/butvideoaudioplaylist_on.png'),
    btnPlaylistFeatureOff : require('../resources/images/playlistheader/butvideoaudioplaylist_off.png'),

    btnPlaylistHeadImportContent : require('../resources/images/playlistheader/playlisthead_import_content.png'),
    btnPlaylistHeadImportContentOn : require('../resources/images/playlistheader/playlisthead_import_content_on.png'),
    btnPlaylistHeadImportContent_active : require('../resources/images/playlistheader/playlisthead_import_content_active.png'),
    btnPlaylistHeadImportContent_rollover : require('../resources/images/playlistheader/playlisthead_import_content_rollover.png'),
    btnPlaylistHeadSearchContent : require('../resources/images/playlistheader/playlisthead_search_content.png'),
    btnPlaylistHeadSearchContentOn : require('../resources/images/playlistheader/playlisthead_search_content_on.png'),
    btnPlaylistHeadSearchContent_active : require('../resources/images/playlistheader/playlisthead_search_content_active.png'),
    btnPlaylistHeadSearchContent_rollover : require('../resources/images/playlistheader/playlisthead_search_content_rollover.png'),
    btnPlaylistHeadPlaylist : require('../resources/images/playlistheader/playlisthead_playlist.png'),
    btnPlaylistHeadPlaylist_active : require('../resources/images/playlistheader/playlisthead_playlist_active.png'),
    btnPlaylistHeadPlaylist_rollover : require('../resources/images/playlistheader/playlisthead_playlist_rollover.png'),
    btnPlaylistHeadPlaylistActions : require('../resources/images/playlistheader/playlisthead_playlistactions.png'),
    btnPlaylistHeadPlaylistActions_active : require('../resources/images/playlistheader/playlisthead_playlistactions_active.png'),
    btnPlaylistHeadPlaylistActions_rollover : require('../resources/images/playlistheader/playlisthead_playlistactions_rollover.png'),
    btnPlaylistHeadWiki : require('../resources/images/playlistheader/wiki.png'),

    btnMobileCollapseUp : require('../resources/images/mobile/mobile_collapse_up.png'),
    btnMobileCollapseDown : require('../resources/images/mobile/mobile_collapse_down.png'),
    btnMobilePlaylistPrev : require('../resources/images/mobile/mobile_playlist_prev.png'),
    btnMobilePlaylistNext : require('../resources/images/mobile/mobile_playlist_next.png'),

    crumb_pgroup : require('../resources/images/breadcrumbs/crumb_pgroup.png'),
    crumb_plist : require('../resources/images/breadcrumbs/crumb_plist.png'),
    crumb_item : require('../resources/images/breadcrumbs/crumb_item.png'),

    owner_badge : require('../resources/images/badge/ui_m_icon_owned.png'),
    subscribed_badge : require('../resources/images/badge/ui_m_icon_subscribed.png'),

    m_icon_pgroup : require('../resources/images/m_icon_package_191217_vA/m_icon_pgroup.png'),
    m_icon_edit_title : require('../resources/images/m_icon_package_191217_vA/m_icon_edit_title.png'),

    settings_bar_pList_height_1_off : require('../resources/images/settingsbar/settings_bar_pList_height_1_off.png'),
    settings_bar_pList_height_1_on : require('../resources/images/settingsbar/settings_bar_pList_height_1_on.png'),

    settings_bar_pList_height_2_off : require('../resources/images/settingsbar/settings_bar_pList_height_2_off.png'),
    settings_bar_pList_height_2_on : require('../resources/images/settingsbar/settings_bar_pList_height_2_on.png'),

    settings_bar_pList_height_3_off : require('../resources/images/settingsbar/settings_bar_pList_height_3_off.png'),
    settings_bar_pList_height_3_on : require('../resources/images/settingsbar/settings_bar_pList_height_3_on.png'),

    settings_bar_pList_height_4_off : require('../resources/images/settingsbar/settings_bar_pList_height_4_off.png'),
    settings_bar_pList_height_4_on : require('../resources/images/settingsbar/settings_bar_pList_height_4_on.png'),

    settings_bar_zoom_size_1_off : require('../resources/images/settingsbar/settings_bar_zoom_size_1_off.png'),
    settings_bar_zoom_size_1_on : require('../resources/images/settingsbar/settings_bar_zoom_size_1_on.png'),

    settings_bar_zoom_size_2_off : require('../resources/images/settingsbar/settings_bar_zoom_size_2_off.png'),
    settings_bar_zoom_size_2_on : require('../resources/images/settingsbar/settings_bar_zoom_size_2_on.png'),

    settings_bar_zoom_size_3_off : require('../resources/images/settingsbar/settings_bar_zoom_size_3_off.png'),
    settings_bar_zoom_size_3_on : require('../resources/images/settingsbar/settings_bar_zoom_size_3_on.png'),

    settings_bar_zoom_size_4_off : require('../resources/images/settingsbar/settings_bar_zoom_size_4_off.png'),
    settings_bar_zoom_size_4_on : require('../resources/images/settingsbar/settings_bar_zoom_size_4_on.png'),

    settings_bar_zoom_size_5_off : require('../resources/images/settingsbar/settings_bar_zoom_size_5_off.png'),
    settings_bar_zoom_size_5_on : require('../resources/images/settingsbar/settings_bar_zoom_size_5_on.png'),

    pListHeader_lock_OFF:require('../resources/images/playlistheader/pListHeader_lock_OFF.png'),
    pListHeader_lock_ON:require('../resources/images/playlistheader/pListHeader_lock_ON.png'),
    pListHeader_lock_NA:require('../resources/images/playlistheader/pListHeader_lock_NOT_AVAIL.png')

};

export default images;
